---
name: Pull request pipeline
on:
  pull_request:
    branches:
      - main

jobs:
  check-conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Obtain next version
        uses: https://github.com/benjaminschmidt/simple-semantic-release@1.2.1
        with:
          create-release: false
