---
name: Pull request pipeline
on:
  pull_request:
    branches:
      - main

jobs:
  check-conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Obtain next version
        uses: https://forgejo.fuzzyhome.net/phaib/simple-semantic-release@1.3.5
        with:
          create-release: false
