# Generated by Django 4.0.6 on 2022-08-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myself',
            name='professional_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
